import type { Metadata } from "next";
import { Geist, Geist_Mono , Inter} from "next/font/google";
import { SessionProvider } from "next-auth/react"
import "./globals.css";
const inter = Inter({
  subsets: ["latin"],
  weight : ['100' , '200', '300' , '400'],
  variable : '--font-inter-sans'
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      <link rel="stylesheet" href="https://cdn.hugeicons.com/font/hgi-stroke-rounded.css" />

      </head>
      <body
        className={`${geistSans.variable} ${inter.className} ${geistMono.variable} antialiased`}

      >
        <SessionProvider>

        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
